name: Continuous Integration

on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set Node.js 14.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          cd js 
          npm ci

      - name: Test
        run: |
          cd js 
          npm run lint
      
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set Node.js 14.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14.x

      - name: Install dependecies
        run: |
          cd js 
          npm ci

      - name: Lint
        run: |
          cd js 
          npm run lint
  
  practice: 
    name: practice
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 
      # docker hubのイメージとアクションを実行
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!

      # シェルをpythonに変更して実行
      - run: |
          import sys
          print(sys.version)
        shell: python

      # エラーが発生してジョブが失敗してもワークフローは失敗しない
      - name: throws error 
        run: exit 1
      

      

